on:
  workflow_call:
    inputs:
      steamworks_sdk_tag:
        required: true
        type: string
      godot_tag:
        required: true
        type: string
    secrets:
      steamworks_sdk_repo:
        required: true
      steamworks_sdk_repo_token:
        required: true


jobs:
  build-windows32:
    runs-on: "windows-latest"
    name: Windows 32 ${{ matrix.name }}
    env:
      SCONSFLAGS: 
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor & Templates
            cache-name: windows-32
            artifact-name: windows
            build-mono: false

          - name: Editor & Templates w/ Mono
            cache-name: windows-32-mono
            artifact-name: windows-mono
            build-mono: true

    steps:
      - uses: actions/checkout@v4

      # Download Godot to start
      - name: Download Godot
        uses: ./.github/actions/godot-download
        with:
          version: ${{ inputs.godot_tag }}

      - name: Preempty Missing bin/
        run: |
          mkdir ./bin/

      # Download GodotSteam Server
      - name: Download GodotSteam Server
        uses: ./.github/actions/godotsteam-download

      # Download Steamworks SDK
      - name: Download Steamworks SDK
        uses: ./.github/actions/steamworks-download
        with:
          path: "steamworks"
          repository: ${{ secrets.steamworks_sdk_repo }}
          token: ${{ secrets.steamworks_sdk_repo_token }}
          ref: ${{ inputs.steamworks_sdk_tag }}

      - name: Move .dll For Mono
        shell: bash
        run: |
          cp ./modules/godotsteam_server/sdk/redistributable_bin/steam_api.dll ./bin/
          ls ./bin/

      # Get that cache set up
      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      # Setup Python and Scons
      - name: Setup Python and Scons
        uses: ./.github/actions/godot-deps

      # Setup Mono
      # Assume Mono is already installed on the runner
      - name: Setup Mono (x86)
        if: ${{ matrix.build-mono }}
        uses: ./.github/actions/godot-windows-mono
        with:
          mono-bcl: "bcl-desktop-win32"
          mono-release: "windows-x86"

      - name: Mono precompilation
        if: ${{ matrix.build-mono }}
        uses: ./.github/actions/godot-windows-build
        with:
          sconsflags: mono_static=yes module_mono_enabled=yes mono_glue=no mono_prefix="$HOME/mono-installs/desktop-windows-x86-release"
          platform: windows
          tools: true

      # Generate Mono glue
      - name: Generate Mono glue code
        if: ${{ matrix.build-mono }}
        run: |
          DRI_PRIME=0 xvfb-run "./bin/godot.x11.tools.64.mono" --generate-mono-glue modules/mono/glue || true

      - name: Set Mono Scons flags
        if: ${{ matrix.build-mono }}
        run: |
          echo "MONO_SCONSFLAGS=module_mono_enabled=yes mono_glue=yes copy_mono_root=yes mono_bcl=$HOME/mono-bcls/desktop-win32-bcl/net_4_x-win32 mono_static=yes" >> $GITHUB_ENV

      # Compiling editors
      - name: Editor compilation (bits=32)
        uses: ./.github/actions/godot-windows-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=32 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-windows-x86-release' || '' }}
          platform: windows
          target: release_debug
          tools: true

      - name: Upload editor (bits=32)
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.artifact-name }}-editor-32

      - name: Clear bin
        run: |
          rm -r -fo bin

      # Compiling templates
      - name: Debug Template compilation (tools=false, bits=32, target=release_debug)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=32 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-windows-x86-release' || '' }}
          platform: windows
          target: release_debug
          tools: false

      - name: Release Template compilation (tools=false, bits=32, target=release)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=32 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-windows-x86-release' || '' }} debug_symbols=no
          platform: windows
          target: release
          tools: false

      - name: Upload Templates (bits=32)
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.artifact-name }}-templates-32

      - name: Clear bin
        shell: pwsh
        run: |
          rm -r -fo bin